apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend-ns
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/sm-cloud-system/global-sookmyung-server:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SPRING_PROFILES_ACTIVE
        - name: DB_DRIVER_CLASS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_DRIVER_CLASS
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MYSQL_ROOT_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: REDIS_PORT
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: JWT_SECRET_KEY
        - name: JWT_ACCESS_TOKEN_EXPIRE_TIME_FOR_GUEST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: JWT_ACCESS_TOKEN_EXPIRE_TIME_FOR_GUEST
        - name: JWT_ACCESS_TOKEN_EXPIRE_TIME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: JWT_ACCESS_TOKEN_EXPIRE_TIME
        - name: JWT_ACCESS_TOKEN_HEADER
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: JWT_ACCESS_TOKEN_HEADER
        - name: JWT_REFRESH_TOKEN_EXPIRE_TIME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: JWT_REFRESH_TOKEN_EXPIRE_TIME
        - name: JWT_REFRESH_TOKEN_HEADER
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: JWT_REFRESH_TOKEN_HEADER
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SMTP_PORT
        - name: SMTP_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SMTP_USERNAME
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: SMTP_PASSWORD
        - name: TZ 
		      value: Asia/Seoul 
        ports:
        - containerPort: 8080