apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend-ns
type: Opaque
data:
  SMTP_PASSWORD: { base64로 인코딩 된 SMTP에 사용할 계정의 패스워드 }
  JWT_SECRET_KEY: { base64로 인코딩 된 JWT 시크릿 키 }
  JWT_ACCESS_TOKEN_HEADER: { base64로 인코딩 된 서비스 내 AccessToken 헤더 이름 }
  JWT_REFRESH_TOKEN_HEADER: { base64로 인코딩 된 서비스 내 RefreshToken 헤더 이름 }
  MYSQL_ROOT_PASSWORD: { base64로 인코딩 된 mysql 패스워드 }
