name: GLOBAL SOOKMYUNG PROD CI/CD
on:
  push:
    branches: [ "prod" ]

jobs:
  prod-ci:
    runs-on: ubuntu-22.04

    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: build
        run: |
          chmod +x gradlew
          ./gradlew build
        shell: bash

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: github container registry login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/global-sookmyung-server:latest